### ISSUE TITLE
Branch lengths not reflective of underlying value

### ISSUE THREAD

**Issue by ells** [CDCgov/MicrobeTrace#61] opened 2018-11-02 18:54 UTC
For some sequence file inputs, there seems to be an issue with the phylogenetic tree view that does not allow the underlying branch length to propagate to the visualization layer. 

When this bug occurs, no scale bar is present and all branch lengths align to the ID label. However, at the same time, the underlying branch length reported by the mouseover function is accurate. These issues are shown in the figure below using the exampleSequences.fasta file in Module 1 of the MicrobeTrace demo files. 
![image](https://user-images.githubusercontent.com/1420108/47934805-cb393580-deae-11e8-8a23-0f2ea3242822.png)

In other input files, the scale bar renders and the branch lengths are reflective of their true value. This is shown below:
![image](https://user-images.githubusercontent.com/1420108/47934938-36830780-deaf-11e8-9a9a-85c4c8a818ec.png)

**Comment by AABoyles** [comment] 2019-02-21 17:43
Duplicate of #24, resolved by ditching Phylotree for TidyTree

**Closed as completed by AABoyles** 2019-02-21 17:43 UTC
Labels: [issue-type] bug
