### ISSUE TITLE
HCV dummy dataset- MT PROD uses the wrong distance field to launch network

### ISSUE THREAD

**Issue by ikb6** [CDCgov/MicrobeTRACE#797] opened 2024-04-10 18:22 UTC
[threshold_links_YSmodified.xlsx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd05PQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bcd28d77980d2e18005bfd6dd39b775e2c84c5b7/threshold_links_YSmodified.xlsx)
When I load 2  HCV dummy files  (a node list and a distance edgelist- see attached file), I want MT to use the field **min_dist** for distance threshold. I load files, select 'min_dist' from drop down, set TN93 to 0.052 (that's their cut-off) and launch. But I get a hairball.
When I go to Settings and check, I realize that the links are being filtered on 'distance' field (I think MT automatically assigns this field?) rather than on min-dist like I asked it to.
When I select min-dist from the drop down menu in Settings, it gives the network that it is supposed to.

Can you check why MT would not use min-dist to begin with even though it is specified at loading? See video with console log below

https://cdc.sharepoint.com/:v:/r/teams/nchhstp-dhap-lb-microbetrace/Shared%20Documents/General/Files%20for%20bug%20reports/Angular_dist_miniHistogram_ZenhubIssue748.mp4?csf=1&web=1&e=gUXxKP

**Comment by dacowan404** [comment] 2024-04-11 17:50
The problem is that when if you specify distance field for link file, MicrobeTrace expects that column named to be 'distance'. If you specify that field with a different name, it records the distance as being 0. So, to fix this bug, you just need to change the name of that column in your excel file. I have found a way to fix this in the code so that field can be named something else, but I need to test it more first.

**Comment by dacowan404** [comment] 2024-04-15 13:31
I have committed and deployed the update to Mossy url so now columns (besides just those named 'distance') can be used to set the distance when loading an edge list.

**Closed as completed** 2024-07-24 17:08 UTC
Labels: [issue-type] bug, high-priority
